module.exports = [
  "list",
  "list-with-links",
  "nav-links",
  "social-icon-links",
  "hero",
  "hero-marketing",
  "hero-article",
  "blockquote",
  "article",
  "figure",
  "video",
  "card-grid",
  "button-group",
  "contact-form",
  "footer",
];
